spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  level:
    web: trace
beatmap-selection:
  file-path: path/
  ssl: false
  local-url: localhost:16113
  osu:
    callback-url: /callback
    oauth:
      id: 80
      token: yourToken
  profiles:
    active: tmp