logging:
  level:
    web: info
beatmap-selection:
  file-path: path/
  ssl: false
  local-url: localhost:16113
  osu:
    callback-url: /callback
    oauth:
      id: 80
      token: yourToken
spring:
  codec:
    max-in-memory-size: 20MB
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 40MB
  jpa:
    properties.hibernate.session.events.log.LOG_QUERIES_SLOWER_THAN_MS: 1
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: update
    show-sql: false
  profiles:
    active: tmp
  task:
    execution:
      pool:
        core-size: 10