logging:
  level:
    web: trace
beatmap-selection:
  file-path: path/
  ssl: false
  local-url: localhost:16113
  osu:
    callback-url: /callback
    oauth:
      id: 80
      token: yourToken

spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 40MB
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  profiles:
    active: tmp