
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://8.210.53.197:52109/map_pool
    username: map_pool
    password: map_pool
    hikari:
      maximum-pool-size: 10  # 数据库连接池最大连接数
      minimum-idle: 5  # 数据库连接池最小空闲连接数
      connection-test-query: SELECT 1  # 数据库连接测试语句

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.HSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true